name: dotnet using calling

on:
  workflow_dispatch:

jobs:

  # build:
  #   uses: anusha414/reusable-demo-workflows/.github/workflows/reusable-dotnetbuild.yml@master

  # test:
  #   uses: anusha414/reusable-demo-workflows/.github/workflows/reusable-dotnettest.yml@master
    
  # run:
  #   uses: anusha414/reusable-demo-workflows/.github/workflows/reusable-dotnetrun.yml@master
  #   with:
  #     FILENAME: Program.csproj

  all:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
      with:
        repository: anusha414/dotnet
        ref: master
        
    - uses: anusha414/reusable-demo-workflows/.github/workflows/reusable-dotnet.yml@master
      with:
        FILENAME: Program.csproj
    
