name: .NET Hello World CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # Adjust based on your .NET version
       
    - name: Build
      run: dotnet run --project Program.csproj
  
